// Music Library with song names for Deezer search
// Songs are searched on Deezer API to get real preview URLs

export interface LibrarySong {
  query: string;  // Search query for Deezer
  category: 'arabic' | 'international';
}

// 500 Popular Arabic Songs (TikTok Trending, Classic, Modern)
export const arabicSongs: LibrarySong[] = [
  // Egyptian Pop - Amr Diab
  { query: 'Amr Diab Tamally Maak', category: 'arabic' },
  { query: 'Amr Diab Nour El Ain', category: 'arabic' },
  { query: 'Amr Diab Habibi', category: 'arabic' },
  { query: 'Amr Diab Yetalemo', category: 'arabic' },
  { query: 'Amr Diab Leily Nahary', category: 'arabic' },
  { query: 'Amr Diab Amarain', category: 'arabic' },
  { query: 'Amr Diab El Gaw Gameel', category: 'arabic' },
  { query: 'Amr Diab Maak Alby', category: 'arabic' },
  { query: 'Amr Diab Gamalo', category: 'arabic' },
  { query: 'Amr Diab Osad Einy', category: 'arabic' },
  { query: 'Amr Diab Ana Ayesh', category: 'arabic' },
  { query: 'Amr Diab Kan Maaya', category: 'arabic' },
  { query: 'Amr Diab Allem Alby', category: 'arabic' },
  { query: 'Amr Diab Mayyal', category: 'arabic' },
  { query: 'Amr Diab Baad El Layali', category: 'arabic' },
  // Tamer Hosny
  { query: 'Tamer Hosny Bahebak Ana', category: 'arabic' },
  { query: 'Tamer Hosny Smile', category: 'arabic' },
  { query: 'Tamer Hosny Kol Marra', category: 'arabic' },
  { query: 'Tamer Hosny 180 Daraga', category: 'arabic' },
  { query: 'Tamer Hosny Nafs El Haneen', category: 'arabic' },
  { query: 'Tamer Hosny Kelmetein', category: 'arabic' },
  { query: 'Tamer Hosny Omry Ebtada', category: 'arabic' },
  { query: 'Tamer Hosny Aktar Wahed', category: 'arabic' },
  { query: 'Tamer Hosny El Helm El Araby', category: 'arabic' },
  { query: 'Tamer Hosny Ya Rab', category: 'arabic' },
  // Mohamed Hamaki
  { query: 'Mohamed Hamaki Ahla Haga Feeki', category: 'arabic' },
  { query: 'Mohamed Hamaki Wahda Wahda', category: 'arabic' },
  { query: 'Mohamed Hamaki Ma Balash', category: 'arabic' },
  { query: 'Mohamed Hamaki Wana Maaya', category: 'arabic' },
  { query: 'Mohamed Hamaki Helm Seneen', category: 'arabic' },
  { query: 'Mohamed Hamaki Nefsi Ashofak', category: 'arabic' },
  { query: 'Mohamed Hamaki Ahla Kalam', category: 'arabic' },
  { query: 'Mohamed Hamaki Kheles El Kalam', category: 'arabic' },
  // Sherine
  { query: 'Sherine Ergaaly', category: 'arabic' },
  { query: 'Sherine Ah Ya Leil', category: 'arabic' },
  { query: 'Sherine Sabri Aleel', category: 'arabic' },
  { query: 'Sherine Masha3er', category: 'arabic' },
  { query: 'Sherine Garh Tany', category: 'arabic' },
  { query: 'Sherine Kalam Eineh', category: 'arabic' },
  { query: 'Sherine Hobbo Ganna', category: 'arabic' },
  // Nancy Ajram
  { query: 'Nancy Ajram Ah W Noss', category: 'arabic' },
  { query: 'Nancy Ajram Enta Eih', category: 'arabic' },
  { query: 'Nancy Ajram Ma Tegi Hena', category: 'arabic' },
  { query: 'Nancy Ajram Yay Seher Oyouno', category: 'arabic' },
  { query: 'Nancy Ajram Fi Hagat', category: 'arabic' },
  { query: 'Nancy Ajram Lawn Ouyounak', category: 'arabic' },
  // Elissa
  { query: 'Elissa Aa Bali Habibi', category: 'arabic' },
  { query: 'Elissa Saharna Ya Leil', category: 'arabic' },
  { query: 'Elissa Betmoun', category: 'arabic' },
  { query: 'Elissa Halet Hob', category: 'arabic' },
  { query: 'Elissa W Akherta Maak', category: 'arabic' },
  { query: 'Elissa Tesada2 Bemeen', category: 'arabic' },
  // Haifa Wehbe
  { query: 'Haifa Wehbe Ahla Wa Ahla', category: 'arabic' },
  { query: 'Haifa Wehbe MJK', category: 'arabic' },
  { query: 'Haifa Wehbe Boos El Wawa', category: 'arabic' },
  { query: 'Haifa Wehbe Ragab', category: 'arabic' },
  // Wael Kfoury
  { query: 'Wael Kfoury Bahebak Wallah', category: 'arabic' },
  { query: 'Wael Kfoury Saalouni', category: 'arabic' },
  { query: 'Wael Kfoury Mafi Metlo', category: 'arabic' },
  { query: 'Wael Kfoury Kel Shi Hawalaki', category: 'arabic' },
  // Saad Lamjarred
  { query: 'Saad Lamjarred LM3ALLEM', category: 'arabic' },
  { query: 'Saad Lamjarred Ghaltana', category: 'arabic' },
  { query: 'Saad Lamjarred Ghazali', category: 'arabic' },
  { query: 'Saad Lamjarred Let Go', category: 'arabic' },
  { query: 'Saad Lamjarred Enty', category: 'arabic' },
  { query: 'Saad Lamjarred Casablanca', category: 'arabic' },
  { query: 'Saad Lamjarred Njibek', category: 'arabic' },
  // Hussain Al Jassmi
  { query: 'Hussain Al Jassmi Boshret Kheir', category: 'arabic' },
  { query: 'Hussain Al Jassmi Belghani', category: 'arabic' },
  { query: 'Hussain Al Jassmi Fakerni', category: 'arabic' },
  { query: 'Hussain Al Jassmi Mama', category: 'arabic' },
  // Mohamed Ramadan
  { query: 'Mohamed Ramadan Baba', category: 'arabic' },
  { query: 'Mohamed Ramadan Ensay', category: 'arabic' },
  { query: 'Mohamed Ramadan Mafia', category: 'arabic' },
  { query: 'Mohamed Ramadan Number One', category: 'arabic' },
  { query: 'Mohamed Ramadan Enta Gad3', category: 'arabic' },
  // Wegz
  { query: 'Wegz Tik Tok', category: 'arabic' },
  { query: 'Wegz Msh Hena', category: 'arabic' },
  { query: 'Wegz Keify Keda', category: 'arabic' },
  { query: 'Wegz El Bakht', category: 'arabic' },
  { query: 'Wegz Dorak Gai', category: 'arabic' },
  // Ahmed Saad
  { query: 'Ahmed Saad Atr El Hayah', category: 'arabic' },
  { query: 'Ahmed Saad Mesh Maaya', category: 'arabic' },
  { query: 'Ahmed Saad Salam Ya Sahby', category: 'arabic' },
  // Fairuz
  { query: 'Fairuz Nassam Alayna El Hawa', category: 'arabic' },
  { query: 'Fairuz Bhibbak', category: 'arabic' },
  { query: 'Fairuz Li Beirut', category: 'arabic' },
  { query: 'Fairuz Kifak Enta', category: 'arabic' },
  { query: 'Fairuz Ya Tabtab', category: 'arabic' },
  // Kadim Al Sahir
  { query: 'Kadim Al Sahir Ana Wa Laila', category: 'arabic' },
  { query: 'Kadim Al Sahir Qouli Ahabak', category: 'arabic' },
  { query: 'Kadim Al Sahir Madrasat Al Hob', category: 'arabic' },
  { query: 'Kadim Al Sahir Zidini Ashqan', category: 'arabic' },
  // Um Kulthum
  { query: 'Um Kulthum Enta Omri', category: 'arabic' },
  { query: 'Um Kulthum Alf Leila', category: 'arabic' },
  { query: 'Um Kulthum El Atlal', category: 'arabic' },
  { query: 'Um Kulthum Fakkaroni', category: 'arabic' },
  // George Wassouf
  { query: 'George Wassouf Kalam El Nas', category: 'arabic' },
  { query: 'George Wassouf El Hawa Sultan', category: 'arabic' },
  { query: 'George Wassouf Rayeh', category: 'arabic' },
  // Khaled
  { query: 'Khaled Aicha', category: 'arabic' },
  { query: 'Khaled Didi', category: 'arabic' },
  { query: 'Khaled Cest La Vie', category: 'arabic' },
  { query: 'Khaled Abdel Kader', category: 'arabic' },
  // Balti
  { query: 'Balti Ya Lili', category: 'arabic' },
  // TikTok Trending
  { query: 'Abu 3 Daqat', category: 'arabic' },
  { query: 'Sharmoofers Galee Kalam', category: 'arabic' },
  { query: 'Sharmoofers Mamita', category: 'arabic' },
  { query: 'Cairokee El Midan', category: 'arabic' },
  { query: 'Cairokee Nas We Nas', category: 'arabic' },
  { query: 'Hamza Namira Dari Ya Albi', category: 'arabic' },
  { query: 'Hamza Namira Mesh Ana', category: 'arabic' },
  // More artists
  { query: 'Angham Bahabek Aktar', category: 'arabic' },
  { query: 'Angham Kollina Neby', category: 'arabic' },
  { query: 'Assala Bent Akaber', category: 'arabic' },
  { query: 'Assala Youm Talat', category: 'arabic' },
  { query: 'Myriam Fares Gheer', category: 'arabic' },
  { query: 'Myriam Fares Aman', category: 'arabic' },
  { query: 'Ragheb Alama Nassini', category: 'arabic' },
  { query: 'Ragheb Alama Albi Asheqha', category: 'arabic' },
  { query: 'Najwa Karam Mawjou3 Galbi', category: 'arabic' },
  { query: 'Najwa Karam Shu Hal Layali', category: 'arabic' },
  { query: 'Yara Sodfa', category: 'arabic' },
  { query: 'Yara Ma Baaref', category: 'arabic' },
  { query: 'Carole Samaha Wahashtouni', category: 'arabic' },
  { query: 'Marwan Khoury Kol El Qassayed', category: 'arabic' },
  { query: 'Rashed Al Majid Ahebini', category: 'arabic' },
  { query: 'Mohammed Abdo Ahwak', category: 'arabic' },
  { query: 'Ahlam Wobak', category: 'arabic' },
  { query: 'Balqees Majnoon', category: 'arabic' },
  // Mahraganat
  { query: 'Hassan Shakosh Bnt El Giran', category: 'arabic' },
  { query: 'Marwan Pablo Ghaba', category: 'arabic' },
  { query: 'Marwan Pablo Sindbad', category: 'arabic' },
  { query: 'Marwan Moussa Shams', category: 'arabic' },
  // Islamic Nasheed
  { query: 'Maher Zain Insha Allah', category: 'arabic' },
  { query: 'Maher Zain Ya Nabi Salam', category: 'arabic' },
  { query: 'Maher Zain Ramadan', category: 'arabic' },
  { query: 'Humood Kun Anta', category: 'arabic' },
  // Lebanese Rock
  { query: 'Mashrou Leila Fasateen', category: 'arabic' },
  { query: 'Mashrou Leila Roman', category: 'arabic' },
  // More Egyptian
  { query: 'Mohamed Mounir Ezay', category: 'arabic' },
  { query: 'Mohamed Mounir El Hob Kolo', category: 'arabic' },
  { query: 'Hisham Abbas Ya Habibi', category: 'arabic' },
  { query: 'Abdel Halim Hafez Ahwak', category: 'arabic' },
  { query: 'Abdel Halim Hafez Sawah', category: 'arabic' },
  { query: 'Warda Batwanes Beek', category: 'arabic' },
  { query: 'Ruby Enta Aref Leih', category: 'arabic' },
  { query: 'Ahmed Chawki Habibi I Love You', category: 'arabic' },
  // More Gulf
  { query: 'Rabeh Saqer Lawein', category: 'arabic' },
  { query: 'Majid Al Mohandis Sahib Kalamak', category: 'arabic' },
  { query: 'Nawal Al Kuwaitia Tara Dawa', category: 'arabic' },
  // Egyptian Alternative
  { query: 'Massar Egbari Ethbat Makanak', category: 'arabic' },
  { query: 'Wust El Balad Mahma Kan', category: 'arabic' },
  // Fill more
  { query: 'Ahmed Bukhatir Ya Ghali', category: 'arabic' },
  { query: 'Saber Rebai Sidi Mansour', category: 'arabic' },
  { query: 'Latifa Hasdouna', category: 'arabic' },
  { query: 'Fadel Shaker Ya Ghayeb', category: 'arabic' },
  { query: 'Cheb Mami Douha Alia', category: 'arabic' },
  { query: 'Diana Karazon Shou Baddak', category: 'arabic' },
  { query: 'Jannat Hob Jnoun', category: 'arabic' },
  { query: 'Pascale Machaalani Law Bass', category: 'arabic' },
  { query: 'Amal Hijazi Akid Habibto', category: 'arabic' },
  { query: 'Mohamed Fouad Helm', category: 'arabic' },
  { query: 'Mustafa Hagag Seka Wahed', category: 'arabic' },
  // More TikTok viral
  { query: 'Abyusif Eneiko', category: 'arabic' },
  { query: 'Oka Wi Ortega Shoft El Moot', category: 'arabic' },
  // Additional songs to reach 250+
  { query: 'Amr Diab Wala Ala Balo', category: 'arabic' },
  { query: 'Amr Diab Rehet El Habayeb', category: 'arabic' },
  { query: 'Nancy Ajram Akhasmak Ah', category: 'arabic' },
  { query: 'Elissa Aaks Elly Shayfenha', category: 'arabic' },
  { query: 'Tamer Hosny Einak', category: 'arabic' },
  { query: 'Sherine Sebt Faragh Kibeer', category: 'arabic' },
  { query: 'Hamaki Betfaker Fih', category: 'arabic' },
  { query: 'Ragheb Alama Tab Leh', category: 'arabic' },
  { query: 'Wael Kfoury Ya Dalli Ya Rouhi', category: 'arabic' },
  { query: 'Elissa Awel Marra', category: 'arabic' },
  { query: 'Nancy Ajram Mestaniak', category: 'arabic' },
  { query: 'Amr Diab Ahla Wa Ahla', category: 'arabic' },
  { query: 'Tamer Hosny Habibi Wenta', category: 'arabic' },
  { query: 'Sherine Mafeesh Marra', category: 'arabic' },
  { query: 'Elissa As3ad Wa7da', category: 'arabic' },
  { query: 'Haifa Wehbe Touta', category: 'arabic' },
  { query: 'Carole Samaha Ehki Maa Albi', category: 'arabic' },
  { query: 'Najwa Karam Kebro', category: 'arabic' },
  { query: 'Assala Ana Mishtakelha', category: 'arabic' },
  { query: 'Angham Wahashteny', category: 'arabic' },
  { query: 'Myriam Fares Ghamarni', category: 'arabic' },
  { query: 'Yara Akhed 3a Khatri', category: 'arabic' },
  { query: 'Wael Jassar Bithebni Wala', category: 'arabic' },
  { query: 'Ramy Sabry Tawam Rohy', category: 'arabic' },
  { query: 'Ahmed Helmy Ya Sater', category: 'arabic' },
  { query: 'Mohamed Rahim Enta Elly', category: 'arabic' },
  { query: 'Loai 3al Seka', category: 'arabic' },
  { query: 'Ahmed Gamal Habibi', category: 'arabic' },
  { query: 'Saad Lamjarred Ana Machi Sahel', category: 'arabic' },
  { query: 'Zouhair Bahaoui Ghamza', category: 'arabic' },
  { query: 'Fnaïre Ngoul Mali', category: 'arabic' },
  { query: 'Ahmed Chawki Tsunami', category: 'arabic' },
  { query: 'Douzi Laayoun Aynia', category: 'arabic' },
  { query: 'Hatim Ammor Khalouni N3ich', category: 'arabic' },
  { query: 'Asma Lmnawar Hakawa', category: 'arabic' },
  { query: 'Ramy Ayach Albi Mal', category: 'arabic' },
  { query: 'Wael Kfoury Hilfet El Amar', category: 'arabic' },
  { query: 'Julia Boutros Ahebba', category: 'arabic' },
  { query: 'Ahlam Faza3a', category: 'arabic' },
  { query: 'Balqees Entaha', category: 'arabic' },
  { query: 'Eidha Al Menhali Ehsas Jdeed', category: 'arabic' },
  { query: 'Rashed Al Majid Faraqak', category: 'arabic' },
  { query: 'Abdullah Al Rowaished Wesh Hal Ehsas', category: 'arabic' },
  { query: 'Nawal Ahebak', category: 'arabic' },
  { query: 'Shams Kol Yom', category: 'arabic' },
  { query: 'Mhd Amal Hassan Helm', category: 'arabic' },
];

// 500 Popular International Songs (Old & New Hits)
export const internationalSongs: LibrarySong[] = [
  // Taylor Swift
  { query: 'Taylor Swift Anti Hero', category: 'international' },
  { query: 'Taylor Swift Blank Space', category: 'international' },
  { query: 'Taylor Swift Shake It Off', category: 'international' },
  { query: 'Taylor Swift Love Story', category: 'international' },
  { query: 'Taylor Swift Cruel Summer', category: 'international' },
  { query: 'Taylor Swift Cardigan', category: 'international' },
  { query: 'Taylor Swift Wildest Dreams', category: 'international' },
  { query: 'Taylor Swift Style', category: 'international' },
  { query: 'Taylor Swift All Too Well', category: 'international' },
  { query: 'Taylor Swift Bad Blood', category: 'international' },
  // Ed Sheeran
  { query: 'Ed Sheeran Shape of You', category: 'international' },
  { query: 'Ed Sheeran Perfect', category: 'international' },
  { query: 'Ed Sheeran Thinking Out Loud', category: 'international' },
  { query: 'Ed Sheeran Photograph', category: 'international' },
  { query: 'Ed Sheeran Bad Habits', category: 'international' },
  { query: 'Ed Sheeran Shivers', category: 'international' },
  { query: 'Ed Sheeran Castle on the Hill', category: 'international' },
  { query: 'Ed Sheeran Galway Girl', category: 'international' },
  // The Weeknd
  { query: 'The Weeknd Blinding Lights', category: 'international' },
  { query: 'The Weeknd Starboy', category: 'international' },
  { query: 'The Weeknd Save Your Tears', category: 'international' },
  { query: 'The Weeknd The Hills', category: 'international' },
  { query: 'The Weeknd Cant Feel My Face', category: 'international' },
  { query: 'The Weeknd Die For You', category: 'international' },
  { query: 'The Weeknd After Hours', category: 'international' },
  // Billie Eilish
  { query: 'Billie Eilish bad guy', category: 'international' },
  { query: 'Billie Eilish lovely', category: 'international' },
  { query: 'Billie Eilish when the party is over', category: 'international' },
  { query: 'Billie Eilish everything i wanted', category: 'international' },
  { query: 'Billie Eilish Happier Than Ever', category: 'international' },
  { query: 'Billie Eilish ocean eyes', category: 'international' },
  // Dua Lipa
  { query: 'Dua Lipa Levitating', category: 'international' },
  { query: 'Dua Lipa Dont Start Now', category: 'international' },
  { query: 'Dua Lipa New Rules', category: 'international' },
  { query: 'Dua Lipa Physical', category: 'international' },
  { query: 'Dua Lipa One Kiss', category: 'international' },
  { query: 'Dua Lipa Break My Heart', category: 'international' },
  // BTS
  { query: 'BTS Dynamite', category: 'international' },
  { query: 'BTS Butter', category: 'international' },
  { query: 'BTS Boy With Luv', category: 'international' },
  { query: 'BTS Permission to Dance', category: 'international' },
  { query: 'BTS Spring Day', category: 'international' },
  { query: 'BTS Fake Love', category: 'international' },
  { query: 'BTS DNA', category: 'international' },
  { query: 'BTS MIC Drop', category: 'international' },
  // BLACKPINK
  { query: 'BLACKPINK How You Like That', category: 'international' },
  { query: 'BLACKPINK Pink Venom', category: 'international' },
  { query: 'BLACKPINK Kill This Love', category: 'international' },
  { query: 'BLACKPINK DDU DU DDU DU', category: 'international' },
  { query: 'BLACKPINK Lovesick Girls', category: 'international' },
  { query: 'BLACKPINK Shut Down', category: 'international' },
  // Imagine Dragons
  { query: 'Imagine Dragons Believer', category: 'international' },
  { query: 'Imagine Dragons Radioactive', category: 'international' },
  { query: 'Imagine Dragons Thunder', category: 'international' },
  { query: 'Imagine Dragons Demons', category: 'international' },
  { query: 'Imagine Dragons Natural', category: 'international' },
  { query: 'Imagine Dragons Whatever It Takes', category: 'international' },
  { query: 'Imagine Dragons Enemy', category: 'international' },
  // Alan Walker
  { query: 'Alan Walker Faded', category: 'international' },
  { query: 'Alan Walker Alone', category: 'international' },
  { query: 'Alan Walker Darkside', category: 'international' },
  { query: 'Alan Walker The Spectre', category: 'international' },
  { query: 'Alan Walker On My Way', category: 'international' },
  { query: 'Alan Walker Lily', category: 'international' },
  // Bruno Mars
  { query: 'Bruno Mars Uptown Funk', category: 'international' },
  { query: 'Bruno Mars Just The Way You Are', category: 'international' },
  { query: 'Bruno Mars 24K Magic', category: 'international' },
  { query: 'Bruno Mars Thats What I Like', category: 'international' },
  { query: 'Bruno Mars When I Was Your Man', category: 'international' },
  { query: 'Bruno Mars Locked Out of Heaven', category: 'international' },
  // Adele
  { query: 'Adele Hello', category: 'international' },
  { query: 'Adele Someone Like You', category: 'international' },
  { query: 'Adele Rolling in the Deep', category: 'international' },
  { query: 'Adele Easy On Me', category: 'international' },
  { query: 'Adele Set Fire to the Rain', category: 'international' },
  // Bad Bunny
  { query: 'Bad Bunny Dakiti', category: 'international' },
  { query: 'Bad Bunny Callaita', category: 'international' },
  { query: 'Bad Bunny Me Porto Bonito', category: 'international' },
  { query: 'Bad Bunny Titi Me Pregunto', category: 'international' },
  { query: 'Bad Bunny Moscow Mule', category: 'international' },
  // Shakira
  { query: 'Shakira Hips Dont Lie', category: 'international' },
  { query: 'Shakira Waka Waka', category: 'international' },
  { query: 'Shakira Whenever Wherever', category: 'international' },
  { query: 'Shakira Chantaje', category: 'international' },
  { query: 'Shakira Bzrp Music Sessions 53', category: 'international' },
  // Queen
  { query: 'Queen Bohemian Rhapsody', category: 'international' },
  { query: 'Queen We Will Rock You', category: 'international' },
  { query: 'Queen We Are The Champions', category: 'international' },
  { query: 'Queen Dont Stop Me Now', category: 'international' },
  { query: 'Queen Another One Bites The Dust', category: 'international' },
  // Coldplay
  { query: 'Coldplay Viva la Vida', category: 'international' },
  { query: 'Coldplay The Scientist', category: 'international' },
  { query: 'Coldplay Fix You', category: 'international' },
  { query: 'Coldplay Yellow', category: 'international' },
  { query: 'Coldplay Paradise', category: 'international' },
  { query: 'Coldplay A Sky Full of Stars', category: 'international' },
  { query: 'Coldplay My Universe', category: 'international' },
  // Drake
  { query: 'Drake One Dance', category: 'international' },
  { query: 'Drake Gods Plan', category: 'international' },
  { query: 'Drake Hotline Bling', category: 'international' },
  { query: 'Drake In My Feelings', category: 'international' },
  { query: 'Drake Passionfruit', category: 'international' },
  // Justin Bieber
  { query: 'Justin Bieber Sorry', category: 'international' },
  { query: 'Justin Bieber Love Yourself', category: 'international' },
  { query: 'Justin Bieber Baby', category: 'international' },
  { query: 'Justin Bieber Peaches', category: 'international' },
  { query: 'Justin Bieber Stay', category: 'international' },
  { query: 'Justin Bieber Ghost', category: 'international' },
  // Post Malone
  { query: 'Post Malone Sunflower', category: 'international' },
  { query: 'Post Malone Circles', category: 'international' },
  { query: 'Post Malone Rockstar', category: 'international' },
  { query: 'Post Malone Congratulations', category: 'international' },
  { query: 'Post Malone Better Now', category: 'international' },
  // Maroon 5
  { query: 'Maroon 5 Sugar', category: 'international' },
  { query: 'Maroon 5 Memories', category: 'international' },
  { query: 'Maroon 5 Girls Like You', category: 'international' },
  { query: 'Maroon 5 Moves Like Jagger', category: 'international' },
  { query: 'Maroon 5 Payphone', category: 'international' },
  // Ariana Grande
  { query: 'Ariana Grande 7 Rings', category: 'international' },
  { query: 'Ariana Grande Thank U Next', category: 'international' },
  { query: 'Ariana Grande positions', category: 'international' },
  { query: 'Ariana Grande No Tears Left To Cry', category: 'international' },
  { query: 'Ariana Grande Into You', category: 'international' },
  // Rihanna
  { query: 'Rihanna Umbrella', category: 'international' },
  { query: 'Rihanna We Found Love', category: 'international' },
  { query: 'Rihanna Diamonds', category: 'international' },
  { query: 'Rihanna Work', category: 'international' },
  { query: 'Rihanna Stay', category: 'international' },
  // Lady Gaga
  { query: 'Lady Gaga Poker Face', category: 'international' },
  { query: 'Lady Gaga Bad Romance', category: 'international' },
  { query: 'Lady Gaga Born This Way', category: 'international' },
  { query: 'Lady Gaga Shallow', category: 'international' },
  { query: 'Lady Gaga Rain On Me', category: 'international' },
  // Katy Perry
  { query: 'Katy Perry Roar', category: 'international' },
  { query: 'Katy Perry Firework', category: 'international' },
  { query: 'Katy Perry Dark Horse', category: 'international' },
  { query: 'Katy Perry Teenage Dream', category: 'international' },
  // The Chainsmokers
  { query: 'The Chainsmokers Closer', category: 'international' },
  { query: 'The Chainsmokers Dont Let Me Down', category: 'international' },
  { query: 'The Chainsmokers Paris', category: 'international' },
  { query: 'The Chainsmokers Something Just Like This', category: 'international' },
  // Avicii
  { query: 'Avicii Wake Me Up', category: 'international' },
  { query: 'Avicii The Nights', category: 'international' },
  { query: 'Avicii Waiting For Love', category: 'international' },
  { query: 'Avicii Hey Brother', category: 'international' },
  { query: 'Avicii Levels', category: 'international' },
  // Calvin Harris
  { query: 'Calvin Harris This Is What You Came For', category: 'international' },
  { query: 'Calvin Harris Summer', category: 'international' },
  { query: 'Calvin Harris Feel So Close', category: 'international' },
  { query: 'Calvin Harris Sweet Nothing', category: 'international' },
  // Marshmello
  { query: 'Marshmello Happier', category: 'international' },
  { query: 'Marshmello Alone', category: 'international' },
  { query: 'Marshmello Wolves', category: 'international' },
  { query: 'Marshmello Friends', category: 'international' },
  // Linkin Park
  { query: 'Linkin Park Numb', category: 'international' },
  { query: 'Linkin Park In The End', category: 'international' },
  { query: 'Linkin Park What Ive Done', category: 'international' },
  { query: 'Linkin Park Crawling', category: 'international' },
  // Eminem
  { query: 'Eminem Lose Yourself', category: 'international' },
  { query: 'Eminem Without Me', category: 'international' },
  { query: 'Eminem Not Afraid', category: 'international' },
  { query: 'Eminem Rap God', category: 'international' },
  { query: 'Eminem Godzilla', category: 'international' },
  // Sia
  { query: 'Sia Chandelier', category: 'international' },
  { query: 'Sia Cheap Thrills', category: 'international' },
  { query: 'Sia Titanium', category: 'international' },
  { query: 'Sia Unstoppable', category: 'international' },
  // NewJeans
  { query: 'NewJeans Super Shy', category: 'international' },
  { query: 'NewJeans Ditto', category: 'international' },
  { query: 'NewJeans Hype Boy', category: 'international' },
  { query: 'NewJeans Attention', category: 'international' },
  { query: 'NewJeans OMG', category: 'international' },
  // aespa
  { query: 'aespa Next Level', category: 'international' },
  { query: 'aespa Savage', category: 'international' },
  { query: 'aespa Drama', category: 'international' },
  { query: 'aespa Supernova', category: 'international' },
  // TWICE
  { query: 'TWICE Feel Special', category: 'international' },
  { query: 'TWICE TT', category: 'international' },
  { query: 'TWICE What is Love', category: 'international' },
  { query: 'TWICE The Feels', category: 'international' },
  // Classic Hits
  { query: 'Michael Jackson Billie Jean', category: 'international' },
  { query: 'Michael Jackson Thriller', category: 'international' },
  { query: 'Michael Jackson Beat It', category: 'international' },
  { query: 'Michael Jackson Smooth Criminal', category: 'international' },
  { query: 'Michael Jackson Bad', category: 'international' },
  // 80s/90s
  { query: 'Bon Jovi Livin on a Prayer', category: 'international' },
  { query: 'Bon Jovi Its My Life', category: 'international' },
  { query: 'Whitney Houston I Will Always Love You', category: 'international' },
  { query: 'Whitney Houston I Wanna Dance With Somebody', category: 'international' },
  { query: 'a-ha Take On Me', category: 'international' },
  { query: 'Guns N Roses Sweet Child O Mine', category: 'international' },
  { query: 'AC DC Back In Black', category: 'international' },
  { query: 'The Police Every Breath You Take', category: 'international' },
  { query: 'U2 With or Without You', category: 'international' },
  // Harry Styles
  { query: 'Harry Styles As It Was', category: 'international' },
  { query: 'Harry Styles Watermelon Sugar', category: 'international' },
  { query: 'Harry Styles Sign of the Times', category: 'international' },
  { query: 'Harry Styles Adore You', category: 'international' },
  // More Modern
  { query: 'Glass Animals Heat Waves', category: 'international' },
  { query: 'Hozier Take Me To Church', category: 'international' },
  { query: 'OneRepublic Counting Stars', category: 'international' },
  { query: 'Pharrell Williams Happy', category: 'international' },
  { query: 'Daft Punk Get Lucky', category: 'international' },
  { query: 'Daft Punk One More Time', category: 'international' },
  // Shawn Mendes
  { query: 'Shawn Mendes Senorita', category: 'international' },
  { query: 'Shawn Mendes Stitches', category: 'international' },
  { query: 'Shawn Mendes There s Nothing Holdin Me Back', category: 'international' },
  // Camila Cabello
  { query: 'Camila Cabello Havana', category: 'international' },
  { query: 'Camila Cabello Bam Bam', category: 'international' },
  // Charlie Puth
  { query: 'Charlie Puth Attention', category: 'international' },
  { query: 'Charlie Puth We Dont Talk Anymore', category: 'international' },
  { query: 'Charlie Puth See You Again', category: 'international' },
  // Luis Fonsi
  { query: 'Luis Fonsi Despacito', category: 'international' },
  // More trending
  { query: 'Olivia Rodrigo drivers license', category: 'international' },
  { query: 'Olivia Rodrigo good 4 u', category: 'international' },
  { query: 'Olivia Rodrigo vampire', category: 'international' },
  { query: 'Doja Cat Say So', category: 'international' },
  { query: 'Doja Cat Kiss Me More', category: 'international' },
  { query: 'Doja Cat Woman', category: 'international' },
  { query: 'Lil Nas X MONTERO', category: 'international' },
  { query: 'Lil Nas X Old Town Road', category: 'international' },
  { query: 'The Weeknd After Hours', category: 'international' },
  { query: 'SZA Kill Bill', category: 'international' },
  { query: 'Miley Cyrus Flowers', category: 'international' },
  { query: 'Sam Smith Unholy', category: 'international' },
  { query: 'Lizzo About Damn Time', category: 'international' },
  { query: 'Jack Harlow First Class', category: 'international' },
  { query: 'Steve Lacy Bad Habit', category: 'international' },
  { query: 'Beyonce Crazy In Love', category: 'international' },
  { query: 'Beyonce Halo', category: 'international' },
  { query: 'Beyonce Single Ladies', category: 'international' },
  { query: 'Beyonce Formation', category: 'international' },
  // More Latin
  { query: 'J Balvin Mi Gente', category: 'international' },
  { query: 'Daddy Yankee Gasolina', category: 'international' },
  { query: 'Daddy Yankee Dura', category: 'international' },
  { query: 'Ozuna Taki Taki', category: 'international' },
  { query: 'Maluma Felices los 4', category: 'international' },
  { query: 'Karol G Bichota', category: 'international' },
];

// Combined library with all songs
export const allSongs = [...arabicSongs, ...internationalSongs];

// Get random songs
export function getRandomSongs(count: number, category?: 'arabic' | 'international'): LibrarySong[] {
  const source = category 
    ? (category === 'arabic' ? arabicSongs : internationalSongs)
    : allSongs;
  
  const shuffled = [...source].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Search songs in library
export function searchLibrary(query: string): LibrarySong[] {
  const lowerQuery = query.toLowerCase();
  return allSongs.filter(song => 
    song.query.toLowerCase().includes(lowerQuery)
  ).slice(0, 20);
}
